### ISSUE TITLE
mParticle.swift uses AnyObject instead of Any

### ISSUE THREAD

**Issue by JonnyLinja** [prolificinteractive/simcoe#25]

**Comment by MichaelCampbell** [comment]
Hey @JonnyLinja this was resolved in https://github.com/prolificinteractive/simcoe/pull/24. Please let us know if you have any questions.

Cheers!

**Comment by JonnyLinja** [comment]
It wasn't resolved. mParticle.swift still uses AnyObject

`public func setUserAttribute(_ key: String, value: AnyObject) -> TrackingResult {
`

**Comment by MichaelCampbell** [comment]
Ah, sorry about that @JonnyLinja. We have this on our radar

**Comment by yoyoyoseob** [comment]
Closing this out with merging of PR #27
